### ISSUE TITLE
4 pwm signals per timer = 16 pwm signals

### ISSUE THREAD

**Issue by silvan2468** [khoih-prog/nRF52_MBED_PWM#2]
Hy

If I have seen right in other forums, it is possible to use 4 pwm signals at the same timer. Of course they will have the same frequency. But then it would be possible to controll up to 16 high speed servos with 330 hz. 
Is this possible with this library? If not, how can I/you adapt this library to do so?

Thanks a lot
Silvan

**Comment by khoih-prog** [comment]
As this is not an issue / bug of this library, I'm closing the topic now and move to Discussions.
